# Example workflow that runs when PR comments are created or edited
name: Link Diff in PR Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  link-diff:
    # Only run on pull request comments
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    
    # Required permissions
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Link diff files in comment
        uses: aki77/pr-comment-diff-linker-action@v1
        with:
          pr-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          token: ${{ secrets.GITHUB_TOKEN }}